# Generated by Django 4.0.3 on 2022-05-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5)),
                ('first_guess', models.CharField(max_length=5)),
                ('second_guess', models.CharField(max_length=5)),
                ('third_guess', models.CharField(max_length=5)),
                ('fourth_guess', models.CharField(max_length=5)),
                ('fifth_guess', models.CharField(max_length=5)),
                ('sixth_guess', models.CharField(max_length=5)),
            ],
        ),
    ]
